### ISSUE TITLE
CTDs in Wyrmstooth

### ISSUE THREAD

**Issue by django747** [m-vlad/Yggdrasil-VR#16] opened 2022-07-18 21:31 UTC
**Describe the bug**
CTDs are encountered when visiting various areas in Wyrmstooth, primarily in the northern and southern ends of the island.

**To Reproduce**
1. Go to Wyrmstooth
2. Visit areas such as Krakevisa
3. Encounter a CTD

**Expected behavior**
It is expected to explore Wyrmstooth without encountering any CTDs.

**Screenshots**
N/A

**Save**
[save.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9135882/save.zip)

**Crash log**
[crash-2022-07-17-22-48-17.log](https://github.com/m-vlad/Yggdrasil-VR/files/9135886/crash-2022-07-17-22-48-17.log)

**Desktop (please complete the following information):**
 - OS version: [e.g. Windows 11, Windows 10] Windows 10 21H2
 - RAM: [e.g. 16gb, 32gb] 32gb
 - CPU: [e.g. Intel i7-9750H] AMD Ryzen 7
 - GPU: [e.g. Nvidia RTX 2060 Mobile] Nvidia RTX 2070 SUPER
 - Storage type Yggdrasil VR is installed on: [e.g. SSD, HDD] SSD
 - Antivirus [e.g. Windows Defender, Bitdefender] Windows Defender

**Additional context**
N/A

**Comment by m-vlad** [comment] 2022-07-18 22:30
Dupe of #12

**Closed by m-vlad** 2022-07-18 22:30 UTC
Labels: bug
